CI.run do
  step "Dependencies", "bundle check"
  step "Native contracts", "bin/native check"
  step "Style: Ruby and Markdown", "bin/rubocop"
  step "Style: Test tools", "bin/rubocop bin/configure bin/setup bin/load-test bin/test-profile bin/image-test bin/images"
  step "Templates: Herb", "bin/erb-check"
  step "Security: Developer tools", "npm audit"
  step "AgentPrism: types and provenance", "npm run check:agents"
  step "AgentPrism: build", "npm run build:agents"
  step "Autoloading", "bin/rails zeitwerk:check"
  step "Security: Gems", "bin/bundler-audit check --update"
  step "Security: JavaScript", "bin/importmap audit"
  step "Security: Brakeman", "bin/brakeman --quiet --no-pager --exit-on-warn --exit-on-error"
  step "Database", "bin/rails db:prepare"
  step "Configuration: workers", "bin/jobs check"
  step "Assets", "bin/rails tailwindcss:build"
  step "Tests: Rails", "bin/rails test"
  step "Tests: Browser", "bin/rails test:system"
  step "Tests: AnyCable", "bin/realtime-test"
  step "Tests: Images", "bin/image-test"
  # Run load measurements separately via bin/load-test or Test diagnostics.
end
