default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: "*"
      threads: <%= Rails.configuration.x.concurrency.job_threads %>
      processes: <%= Rails.configuration.x.concurrency.job_concurrency %>
      polling_interval: 1

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
